### ISSUE TITLE
vpm fails to install

### ISSUE THREAD

**Issue by atomikpanda** [hovsater/homebrew-formulas#1]
`brew install vpm`
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/kevinsjoberg/homebrew-formulas/vpm.rb:5:in `<class:Vpm>'
Please report this to the kevinsjoberg/formulas tap!
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:85:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:93:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/sha1.rb:3:in `sha1'
/usr/local/Homebrew/Library/Taps/kevinsjoberg/homebrew-formulas/vpm.rb:5:in `<class:Vpm>'
/usr/local/Homebrew/Library/Taps/kevinsjoberg/homebrew-formulas/vpm.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:241:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:406:in `find_with_priority'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:45:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:41:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:41:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:107:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

**Comment by hovsater** [comment]
Thanks, I've not maintained vpm for quite some time, but I'll take a look at this in the near future.

**Comment by tregusti** [comment]
Same problem with `m`. =/

**Comment by hovsater** [comment]
@tregusti long time no see! 😄  I'll update both formulas before I leave for Thailand. 👍
